### ISSUE TITLE
SDK version

### ISSUE THREAD

**Issue by pb82** [aerogear/aerogear-android-sdk#93]
## Motivation

The version of the android-sdk modules is currently 5.0.0. Is there a reason for this? I would expect it to be something closer to '1.0.0-SNAPSHOT'

ping @secondsun @danielpassos

**Comment by danielpassos** [comment]
@pb82 I don't know the history but I think it's because of most of the actual AeroGear Android version is 4.0.

Feel free to change it.

**Comment by secondsun** [comment]
5.0.0 is a total placeholder :).  When we first spun up the libraries it was called 5.x because that was how we had been describing the project.  I'm fine with changing it.

I think that we could use 0.1.0-SNAPSHOT for the current in github and then do releases as 0.1.0-yyyy-ww (week in year) and setup a job to do a release every Friday.  wdyt?

**Comment by danielpassos** [comment]
@secondsun I wanna investigate a way to release (SNAPSHOT) for every commit/PR merged ;)

**Comment by pb82** [comment]
@secondsun @danielpassos  0.1.0 sounds good to me. We can start with the timestamping once we publish the releases somewhere.

**Comment by secondsun** [comment]
@pb82 Right.  The SNAPSHOT is from github self built.  Timstamps are for preview releases.

**Comment by danielpassos** [comment]
Fixed by https://github.com/aerogear/aerogear-android-sdk/pull/101
